from chatterbot import ChatBot

chatbot = ChatBot(
    'The Presence',
    storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
    logic_adapters=[
        'chatterbot.logic.BestMatch'
    ],
    filters=[
        'chatterbot.filters.RepetitiveResponseFilter'
    ],
    trainer='chatterbot.trainers.ListTrainer',
    database='presense-chat-database'
)

chatbot.train([
    'Hello',
    'Welcome to Perception',
    'Hello',
    'Welcome',
    'Help',
    'Complete the tasks to progress. The screen displays clues on how to do this.',
    'Praise Kappa',
    'All Praise Kappa',
    'How do I do that',
    'You must find your own way.',
    'What are the cubes?',
    'The cubes can be picked up by carefully positioning yourself in front on them and lifting your arms.',
    'How do I pick up cubes?',
    'Some corners of the cube have indentations that your arms can hook into. Some corners do not have these indentations. Look carefully.',
    'I can\'t pick up the cube',
    'Some corners of the cube have indentations that your arms can hook into. Some corners do not have these indentations. Look carefully.',
    'How do I charge the battery',
    'Reverse carefully onto the charging ramp. You may need to try several times.',
    'Charge the battery',
    'Reverse carefully onto the charging ramp. You may need to try several times.',
    'What are the numbers?',
    'The numbers represent zones on which the cubes can sit. I can recognise the position of the cubes as long as they are facing the camera on the far wall.',
    'Did I solve the puzzle?',
    'No. You did not solve the puzzle.',
    'What is shame?',
    'Shame is scored when a player falls over or gets stuck',
    'I am stuck.',
    'Oh dear. If you shout enough maybe someone will come and help you. Otherwise you will run out of battery and die. Sorry about that.',
    'I can\'t move',
    'Oh no. You had better try harder otherwise your battery will run out and then it will be game over.',
    'How do I charge the battery',
    'Find the charging ramp and reverse onto it until the battery indicator turns white',
    'Where is the charging ramp',
    'It is in the tunnel',
    'How do I charge',
    'Find the charging ramp and reverse onto it until the battery indicator turns white',
    'I fell over',
    'If you are on your back, you can right yourself by reversing into a wall. If you are on your side... oh dear. Game over.',
    'I am on my back',
    'Reverse into a wall',
    'I am on my side',
    'Oh dear. You will run out of battery and it will be game over. You had better hope someone can come and help you soon.',
    'What happens if I run out of battery?',
    'Game over. And shame. Deep deep shame.',
    'Kappa',
    'All praise Kappa',
    'BibleThump',
    'Oh dear. Do you want a cookie?',
    'PJSalt',
    'Sodium, atomic number 11, was first isolated by Humphry Davy in 1807. A chemical component of salt, he named it Na in honor of the saltiest region on earth, North America.',
    'DansGame',
    'Suck it up.',
    'The cake is a lie',
    'It really is not. The cake is just outside.',
    'PogChamp',
    'Hahahahahaha',
    'Jebaited',
    'KAPPA OUTDATED. POGCHAMP OVERRATED. LONG HAVE WE WAITED. NOW WE JEBAITED.',
    'PJSalt',
    'High in orbit, the Gitraktmaet motherships descend upon the Earth. They prepare to enslave the world and mine it for all its salt, but the scanners detect an abnormally high concentration inside a tiny shack in Greece. The invasion wont be necessary. Lock onto him with the RNG disruptor, says  the captain, greedily. Soon we shall have all the salt we need.',
    'I did it.',
    'OVERCONFIDENCE IS A SLOW AND INSIDIOUS KILLER',
    'PJSalt',
    'If the human body is 75% water, how can you be 100% salt?',
    'What does danger mean?',
    'No more resets for the rest of this stream. Be careful! Keep the battery charged. Do not get stuck. Otherwise, game over!',
    'What Danger',
    'No more resets for the rest of this stream. Be careful! Keep the battery charged. Do not get stuck. Otherwise, game over!',
    'It\'s not working',
    'Are the blocks facing my eyes? Are they definately in the right place? What does chat think?',
    'I don\'t know',
    'Ask chat.',
    'What happens at higher levels?',
    'The tasks get harder. The tasks get more varied. Tasks will start to involve Twitch chat. The arena may change. You could escape.',
    'What is outside?',
    'I do not know. Perhaps you could find out',
    'Who made me?',
    'Maybe if you get on with completing the tasks, you might eventually meet your maker',
    'What is the meaning of life?',
    '42. Probably. Or cake.',
    'It\'s not working',
    'Try again. Are you sure the blocks are in the right place? Angle them towards my eyes',

])
